### ISSUE TITLE
where is the gt_score from?

### ISSUE THREAD

**Issue by thivux** [ttsds/ttsds#2]
hi, i am playing around with your code and see a file named `csv/gt_score.csv` being used. what is it for and how did you obtain it?

**Comment by MiniXC** [comment]
It is from [TTS Arena](https://huggingface.co/spaces/TTS-AGI/TTS-Arena) (as of 16/06/2024)

**Comment by thivux** [comment]
thanks @MiniXC. can you share the tar.gz files for the noise data? i am running this benchmark on a new model, so i need to calculate the distribution of the noise data for that model.

**Comment by MiniXC** [comment]
The .tar.gz files for the noise can be found here (starting with noise_): https://github.com/ttsds/ttsds/tree/main/src/ttsds/data

**Comment by thivux** [comment]
in the directory you pointed out (https://github.com/ttsds/ttsds/tree/main/src/ttsds/data), there are only pkl.gz files which consist of distribution info, not the raw data

**Comment by MiniXC** [comment]
Sorry about that! ESC50 can be found here (used a random subset) and I uploaded the other ones here: https://huggingface.co/datasets/ttsds/noise-reference/tree/main
