### ISSUE TITLE
Installing from pip

### ISSUE THREAD

**Issue by ecooper7** [ttsds/ttsds#3]
Hello, thanks very much for your nice paper and for sharing your code!  I am trying to do a basic installation of ttsds using pip.  I have an environment with Python 3.9.0 and all of the system dependencies (ffmpeg automake autoconf unzip sox gfortran subversion libtool) already installed.  I ran `pip install ttsds` to do the installation, and then in Python when I run `import ttsds` I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/SLC/users/ecooper/miniconda3/envs/ttsds/lib/python3.9/site-packages/ttsds/__init__.py", line 25, in <module>
    from ttsds.benchmarks.speaker.dvector import DVectorBenchmark
  File "/home/SLC/users/ecooper/miniconda3/envs/ttsds/lib/python3.9/site-packages/ttsds/benchmarks/speaker/dvector.py", line 12, in <module>
    with importlib.resources.path("ttsds", "data") as dp:
  File "/home/SLC/users/ecooper/miniconda3/envs/ttsds/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/SLC/users/ecooper/miniconda3/envs/ttsds/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/SLC/users/ecooper/miniconda3/envs/ttsds/lib/python3.9/site-packages/ttsds/data'
```

Any advice for resolving this?  Did I miss any steps?  I did get one error during the pip installation:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
timm 1.0.7 requires torchvision, which is not installed.`  I am not sure whether this is the dependency conflict related to fairseq that was mentioned in the README, but it doesn't look like the pip installation tried to install fairseq -- should I be manually installing fairseq as a prerequisite before trying the pip installation?

Thanks in advance for any advice or suggestions.

**Comment by MiniXC** [comment]
Regarding the error, it seems I used ``importlib.resources`` incorrectly - I don't know why it worked for me locally. It should be fixed in 0.0.4, can you try if it works when you upgrade ttsds?

> should I be manually installing fairseq as a prerequisite before trying the pip installation?

fairseq is only required if you want to use the UTMOS benchmark (which is not included in the official benchmark)
I will change the package such that fairseq is an optional dependency with the next major update.

**Comment by ecooper7** [comment]
Thanks so much, I was able to install and `import ttsds` now!

Next, trying to run the code, I have a few more questions.  Ultimately I would like to be able to run the pretrained predictor on my own audio sample (or a directory of audio samples) and get the overall score(s) as output.  Does the library have some built-in function to do this easily?  (I can see that I may have to create a DirectoryDataset containing both .wavs and corresponding .txt transcripts, presumably for the ASR WER component -- is there some way to disable the ASR WER components and exclude that from the final score calculation?)

But first, I'd like to try to reproduce the results in the paper.  In this github codebase I can see the `examples` directory with some scripts under `v2`.  When I try to run `setup.sh` I get the following error:

```
Cloning into 'v2-evaluation'...
git@hf.co: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Do I need to create some credentials or do some other setup in order to be able to run this?

**Comment by MiniXC** [comment]
Great that the install works now!
v2_evaluation is work in progress and I cannot currently share the dataset.
I have added [examples/getting_started](https://github.com/ttsds/ttsds/tree/main/examples/getting_started), which should be easier to customise for your needs. If you want to use directories without text, try installing from the github directly (latest version is not pushed to pypi atm) and use the ``--no-text`` flag.

**Comment by MiniXC** [comment]
Thanks for using ttsds already, I'll close this issue for now. Please feel free to open another one if there are any other problems!
