### ISSUE TITLE
Some errors in your paper

### ISSUE THREAD

**Issue by Mira1sen** [ttsds/ttsds#5]
Hi, I think the formula is mistaked in the paper 2.4 section, it should be W_noise / W_real + W_noise which is defined in your code.
<img width="364" alt="image" src="https://github.com/user-attachments/assets/50b3a662-4abd-4d67-9c37-ca605a1495e9">
I think, when the W_noise is large the score should be larger too.

**Comment by MiniXC** [comment]
Yes, as you point out it should be as follows, fixed it on arxiv. Thank you for reporting this!
<img width="230" alt="image" src="https://github.com/user-attachments/assets/10ecf8c9-b947-4e49-9a1f-9a9bc27f98db">
